hard_tabs = true
tab_spaces = 2
use_small_heuristics = "Max"
max_width = 120
fn_params_layout = "Compressed"
fn_single_line = true
newline_style = "Unix"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
